version: "3.8"

services:
  nextjs:
    container_name: flame-portfolio-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped
